spring:
  application:
    name: SpringServer
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: 'jdbc:postgresql://localhost:5432/whisper'
    driver-class-name: org.postgresql.Driver
    username: 'postgres'
    password: 'postgres'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.globally_quoted_identifiers: true
server:
  port: 8081
  address: '0.0.0.0'
logging:
  level:
    by.bsuir.whisper.server.*: debug